[package]
name = "momento"
version = "0.1.0"
authors = ["momento"]
edition = "2018"
description = "Client SDK for Momento services"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/momentohq/client-sdk-rust"
homepage = "https://gomomento.com/"

[workspace]
members = [
  ".",
  "test-util"
]

exclude = [ "example" ]

[dependencies]
momento-protos = { version = "0.84.1" }
log = "0.4"
hyper = { version = "0.14" }
h2 = { version = "0.3" }
tonic = { version = "0.10", features = ["tls", "tls-roots", "tls-webpki-roots"] }
jsonwebtoken = "8.3"
rand = "0.8.5"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
base64 = "0.21"
futures = "0"
zstd = "0.12.4"

[dev-dependencies]
base64-url = "2"
env_logger = "0"
tokio = { version = "1", features = ["full"] }
tokio-test = "0"
uuid = { version = "1", features = ["v4"] }
futures = "0"
anyhow = "1"
momento-test-util = { path = "test-util" }
